name: Python CI

on:
  workflow_dispatch:  # Only runs when manually triggered

jobs:
  test_and_publish:
    runs-on: ubuntu-latest  # Latest Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to v3

    - name: Set up Python
      uses: actions/setup-python@v4  # Use the latest version
      with:
        python-version: '3.9'  # Specify Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r workflow.txt  # Install dependencies

    - name: Verify test discovery
      run: |
        python -m pytest --collect-only  # List tests without running them

    - name: Run tests
      run: |
        mkdir -p pytest-output
        python -m pytest test.py --maxfail=1 --disable-warnings -q --junitxml=pytest-output/results.xml
      continue-on-error: true  # Allow failure to be checked in the next step

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: pytest-output/results.xml

    - name: Check if tests passed
      id: test_status
      run: |
        if grep -q "<failure" pytest-output/results.xml; then
          echo "Tests failed, skipping publish."
          exit 1
        else
          echo "Tests passed, proceeding with PyPI publish."
        fi

    - name: Publish to PyPI
      if: success()
      run: |
        python -m pip install --upgrade setuptools wheel twine
        python setup.py sdist bdist_wheel
        twine upload dist/*
      env:
        TWINE_USERNAME: __token__  # Use __token__ for API authentication
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}  # GitHub secret for API token
